### ISSUE TITLE
Problem with writing more then 16 bytes.

### ISSUE THREAD

**Issue by orange-beans** [nimaltd/ee24#10]
**Chipset:** STM32F410
**EEPROM Chip:** EE24AT02 (EE24_2KBIT)

Problem occurs when try to write **more than 16 bytes**:
Code:
```javascript
  for (uint32_t i = 0; i < 32; i ++) {
    EEPROM_DATA[i] = i;
  }
  if (EE24_Init(&ee24, &hi2c1, EE24_ADDRESS_DEFAULT))
  {
    EE24_Write(&ee24, 0, EEPROM_DATA, 32, 1000);
  }
```
Result:
```javascript
10 11 12 13 14 15 16 17
18 19 1A 1B 1C 1D 1E 1F
10 11 12 13 14 15 16 17
18 19 1A 1B 1C 1D 1E 1F
```
While the correct result should be:
```javascript
00 01 02 03 04 05 06 07
08 09 0A 0B 0C 0D 0E 0F
10 11 12 13 14 15 16 17
18 19 1A 1B 1C 1D 1E 1F
```

What might be the problem?

**Comment by nimaltd** [comment]
hi. let me check the code again. but someone told me check its and it works fine

**Comment by Andrew170285** [comment]
A similar problem. STM32F407, 24LC02, RTOS

**Comment by Andrew170285** [comment]
In the ee24.c file, line 104
98	    w = EE24_PSIZE - (Address  % EE24_PSIZE);
99	    if (w > Len)
100	    {
101	    	w = Len;
102	    }
103 #if ((EE24_SIZE == EE24_1KBIT) || (EE24_SIZE == EE24_2KBIT))
104 if (HAL_I2C_Mem_Write(Handle->HI2c, Handle->Address, Address, I2C_MEMADD_SIZE_8BIT, Data, Len, Timeout) == HAL_OK) 
_____________________________________________________________________________________________________________^
replace Len with w

**Comment by nimaltd** [comment]
@Andrew170285 okay. I will check it soon. Thanks for report.

**Comment by nimaltd** [comment]
it has been fixed and I added WP pin.

**Comment by orange-beans** [comment]
Working great after updates, thanks!

**Comment by nimaltd** [comment]
Your welcome
