### ISSUE TITLE
24c08 and EEPROM24XX_Save

### ISSUE THREAD

**Issue by kko123** [nimaltd/ee24#2]
I fill first 16 bytes from this code:
```
uint8_t	ReadEEPROM[16];
ReadEEPROM[0] = eeprom.ip[0];
ReadEEPROM[1] = eeprom.ip[1];
ReadEEPROM[2] = eeprom.ip[2];
ReadEEPROM[3] = eeprom.ip[3];
ReadEEPROM[4] = eeprom.sn[0];
ReadEEPROM[5] = eeprom.sn[1];
ReadEEPROM[6] = eeprom.sn[2];
ReadEEPROM[7] = eeprom.sn[3];
ReadEEPROM[8] = eeprom.gw[0];
ReadEEPROM[9] = eeprom.gw[1];
ReadEEPROM[10] = eeprom.gw[2];
ReadEEPROM[11] = eeprom.gw[3];										
ReadEEPROM[12] = eeprom.srvip[0];
ReadEEPROM[13] = eeprom.srvip[1];
ReadEEPROM[14] = eeprom.srvip[2];
ReadEEPROM[15] = eeprom.srvip[3];
EEPROM24XX_Save(0,ReadEEPROM,sizeof(ReadEEPROM));
```
then i trying to fill another part of page:
```
ReadEEPROM[0] = (uint8_t)((eeprom.api_port & 0xFF00) >> 8);
ReadEEPROM[1] = (uint8_t)(eeprom.api_port & 0x00FF);										
ReadEEPROM[2] = (uint8_t)((eeprom.srvport & 0xFF00) >> 8);
ReadEEPROM[3] = (uint8_t)(eeprom.srvport & 0x00FF);										
EEPROM24XX_Save(16,ReadEEPROM,4);

```
when I read the first page some data was corrupted (netInfo.gw)

```
EEPROM24XX_Load(0,ReadEEPROM,sizeof(ReadEEPROM));
netInfo.ip[0] = ReadEEPROM[0];
netInfo.ip[1] = ReadEEPROM[1];
netInfo.ip[2] = ReadEEPROM[2];
netInfo.ip[3] = ReadEEPROM[3];
netInfo.sn[0] = ReadEEPROM[4];
netInfo.sn[1] = ReadEEPROM[5];
netInfo.sn[2] = ReadEEPROM[6];
netInfo.sn[3] = ReadEEPROM[7];
netInfo.gw[0] = ReadEEPROM[8];
netInfo.gw[1] = ReadEEPROM[9];
netInfo.gw[2] = ReadEEPROM[10];
netInfo.gw[3] = ReadEEPROM[11];		
servip[0] = ReadEEPROM[12];
servip[1] = ReadEEPROM[13];
servip[2] = ReadEEPROM[14];
servip[3] = ReadEEPROM[15];
		
EEPROM24XX_Load(16,ReadEEPROM,4);
api_port = ((uint16_t)ReadEEPROM[0] << 8) | ReadEEPROM[1];
servport = ((uint16_t)ReadEEPROM[2] << 8) | ReadEEPROM[3];
```
Which problem with this? If i used only first 16 bytes all is ok. When i trying to fiil more pages i received data coruption in first page.

**Comment by nimaltd** [comment]
hello. did you config eeprom24xxconfig.h ?
#define		_EEPROM_SIZE_KBIT       8

**Comment by kko123** [comment]
sure. I think the error in (uint16_t)_EEPROM_ADR|(Address&0x0003),Address>>2
High address bits must be in HW_ADR, but you used low. What do you think?

**Comment by nimaltd** [comment]
Please test that and tell me. I dont have 2408 now . Thank youOn Sep 8, 2019 2:57 PM, kko123 <notifications@github.com> wrote:sure. I think the error in (uint16_t)_EEPROM_ADR|(Address&0x0003),Address>>2
High address bits must be in HW_ADR, but you used low. What do you think?

**Comment by igorzhur727** [comment]
Hello! 
Thank you for your work!
But let me amend.
If we use a 24LC16 chip with a page size of 16 bytes, then when writing 4 bytes from address 14, 2 bytes will be written to addresses 14 and 15 and the other two bytes will be written at the beginning of the page to addresses 0 and 1. This memory feature is described in the datasheet. I corrected the code to write correctly.

bool EE24xx_Write(uint16_t address, uint8_t *data, size_t len, uint32_t timeout)
{
  uint16_t  p, b, w;
  uint16_t  start_num_of_page;
  uint16_t  end_num_of_page;
  uint16_t  end_adr_of_page;
  uint32_t  startTime = HAL_GetTick();
  // Если память занята то ждем тайм-аут
  while (ee24_lock == 1)
  {
    if (HAL_GetTick() - startTime >= timeout) 
      return false;
    ee24_delay(1);
  }
//------------------------------------------------------------------------------
  ee24_lock = 1; 
//------------------------------------------------------------------------------
  #if	(_EEPROM_USE_WP_PIN==1)
  HAL_GPIO_WritePin(_EEPROM_WP_GPIO, _EEPROM_WP_PIN,GPIO_PIN_RESET);
  #endif	
//------------------------------------------------------------------------------
  while(1)
  {
    p = len / _EEPROM_PSIZE; // число страниц для записи
    b = len % _EEPROM_PSIZE; // остаток байт на странице

    if( p > 0) w = _EEPROM_PSIZE;   // Если число записываемых байт больше чем размер страницы то пишем только одну страницу
    else       w = b;               // Если число записываемых байт меньше чем размер страницы то пишем это число байт
    //
    start_num_of_page = (long)(address / _EEPROM_PSIZE);       // страница где начинается запись
    end_num_of_page   =(long)((address+w) / _EEPROM_PSIZE);    // страница где заканчивается запись
    //
    if (end_num_of_page > start_num_of_page) 
    { // данные на страницу не вмещаются. пишем их раздельно. Вычисляем остаток байт на странице.
      end_adr_of_page = ((start_num_of_page+1) * _EEPROM_PSIZE)-1; // Конечный адресс на странице.
      w = (end_adr_of_page - address)+1; 
    }
    
    #if ((_EEPROM_SIZE_KBIT==1) || (_EEPROM_SIZE_KBIT==2))
    if (HAL_I2C_Mem_Write(&_EEPROM_I2C, _EEPROM_ADDRESS, address, I2C_MEMADD_SIZE_8BIT, data, w, 100) == HAL_OK)
    #elif (_EEPROM_SIZE_KBIT==4)
    if (HAL_I2C_Mem_Write(&_EEPROM_I2C, _EEPROM_ADDRESS | (((address & 0x0100) >> 7)), (address & 0xff), I2C_MEMADD_SIZE_8BIT, data, w, 100) == HAL_OK)
    #elif (_EEPROM_SIZE_KBIT==8)
    if (HAL_I2C_Mem_Write(&_EEPROM_I2C, _EEPROM_ADDRESS | (((address & 0x0300) >> 7)), (address & 0xff), I2C_MEMADD_SIZE_8BIT, data, w, 100) == HAL_OK)
    #elif (_EEPROM_SIZE_KBIT==16)
    if (HAL_I2C_Mem_Write(&_EEPROM_I2C, _EEPROM_ADDRESS | (((address & 0x0700) >> 7)), (address & 0xff), I2C_MEMADD_SIZE_8BIT, data, w, 100) == HAL_OK)		
    #else
    if (HAL_I2C_Mem_Write(&_EEPROM_I2C, _EEPROM_ADDRESS, address, I2C_MEMADD_SIZE_16BIT, data, w, 100) == HAL_OK)
    #endif
    {
      ee24_delay(10);
      len -= w;
      data += w;
      address += w;
      if (len == 0)
      {
        #if (_EEPROM_USE_WP_PIN==1)
        HAL_GPIO_WritePin(_EEPROM_WP_GPIO, _EEPROM_WP_PIN, GPIO_PIN_SET);
        #endif
        ee24_lock = 0;
        return true;
      }
      if (HAL_GetTick() - startTime >= timeout) 
      {
        ee24_lock = 0;
        return false;
      }
    }
    else
    {
      #if (_EEPROM_USE_WP_PIN==1)
      HAL_GPIO_WritePin(_EEPROM_WP_GPIO, _EEPROM_WP_PIN, GPIO_PIN_SET);
      #endif
      ee24_lock = 0;
      return false;		
    }
  }
}

**Comment by nimaltd** [comment]
@igorzhur727  . this is fixed now. please try again with 2.1.0
