### ISSUE TITLE
Lib not read or write value

### ISSUE THREAD

**Issue by leech001** [nimaltd/ee24#5]
Hi, i try this code
```
if (ee24_isConnected()) {
        uint8_t memory_ready = 111;
        ee24_write(0, &memory_ready, sizeof(memory_ready), 100);
        ee24_read(0, &memory_ready, sizeof(memory_ready), 100);
    }
```
after finish running code value of memory_ready is '0'.
But all function return is TRUE.

Please help.

**Comment by nimaltd** [comment]
Hello. It's work fine
I check it now. and its ok.

**Comment by leech001** [comment]
Excuse me. You were right. It turned out to be a bad chip, replaced and everything worked. If there is time, please add functions for writing different types of data (uint_16, uint_32, double ...).

**Comment by nimaltd** [comment]
You can convert anythings to (uint8_t*)
